import type { Metadata } from "next"
import "./globals.css"

import Navbar from "./ui/navbar"
import Footer from "./ui/footer"
import Separator from "./ui/separator"

export const metadata: Metadata = {
    title: "Mint-Bricks | Buy & Sell LEGO",
    description: "Generated by create next app",
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <Separator />
                <main className="flex px-20 bg-mint-bricks-main">
                    {children}
                </main>
                <Separator />
                <Footer />
            </body>
        </html>
    )
}
