import type { Metadata } from "next"
import "./globals.css"

import Navbar from "./ui/Navbar"
import Footer from "./ui/Footer"
import Separator from "./ui/Separator"

export const metadata: Metadata = {
	title: "Mint-Bricks | Buy & Sell LEGO",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<Separator />
				<main>{children}</main>
				<Separator />
				<Footer />
			</body>
		</html>
	)
}
